[database]
    username="database username"
    password="database password"
    address= "database address"
    port="database port"

[sentry]
    dsn="sentry dsn"

[secret]
    session="your session key"

[oauth.github]
    id="github client id"
    secret="github secret id"
    redirect="github redirect url"