[database]
    username="database username"
    password="database password"
    address= "database address"
    port="database port"

[scylla]
    port="9042"
    hosts=["host1", "host2"]

[store]
    address="redis address"
    password="redus password"
    db=0

[sentry]
    dsn="sentry dsn"

[secret]
    session="your session key"
    jwtkey="your jwt secret key"

[oauth.github]
    id="github client id"
    secret="github secret id"
    redirect="github redirect url"